version: '3.5'
services:
  task.space.postgres:
    image: postgres:14-alpine
    container_name: task.space.postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
      POSTGRES_DB: task-space
    ports:
      - 5432:5432
    volumes:
      - task.space.postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d test" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - task.space

  task.space.pgadmin:
    image: dpage/pgadmin4
    container_name: task.space.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "keks@htmlacademy.local"
      PGADMIN_DEFAULT_PASSWORD: "test"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - 8082:80
    networks:
      - task.space

volumes:
  task.space.postgres:

networks:
  task.space:
    driver: bridge
