version: '3.5'
services:
  taskforce.users.mongo:
    image: mongo
    restart: always
    container_name: taskforce.users.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: taskforce-users

    ports:
      - 27017:27017

    volumes:
      - taskforce.mongo.users:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/taskforce-users --quiet
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  taskforce.mongo.users:
